#!/usr/bin/env python3
"""
update_version.py
Reads info.json and writes the mod version to core/utils/version.lua for runtime use.

To update the version in runtime code, run:
    python update_version.py
This will update core/utils/version.lua with the current version from info.json.
Do NOT edit core/utils/version.lua manually.

"""
import json
import os

# Paths
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
info_path = os.path.join(root, 'info.json')
lua_out_path = os.path.join(root, 'core', 'version.lua')

# Read info.json
with open(info_path, 'r', encoding='utf-8') as f:
    info = json.load(f)

version = info.get('version', '0.0.0')

# Write version.lua
with open(lua_out_path, 'w', encoding='utf-8') as f:
    f.write(f'-- This file is auto-generated by update_version.py\n')
    f.write(f'return "{version}"\n')

print(f"Wrote version {version} to {lua_out_path}")
