local Cache = require("core.cache.cache")
local mock_player_data = require("tests.mocks.mock_player_data")

describe("Cache module", function()
  it("should store and retrieve values", function()
    local _ = mock_player_data.create_mock_player_data()
    Cache.set("test_key", 123)
    assert.equals(Cache.get("test_key"), 123)
  end)

  it("should return nil for missing keys", function()
    local _ = mock_player_data.create_mock_player_data()
    assert.is_nil(Cache.get("nonexistent_key"))
  end)
end)
