---@diagnostic disable: undefined-global, lowercase-global, duplicate-set-field, duplicate-doc-field, assign-type-mismatch, param-type-mismatch, return-type-mismatch, redundant-parameter, missing-return, cast-local-type, need-check-nil, deprecated, undefined-field, redefined-local, unused-local, unused-function, unused-label, trailing-space
--- @class defines
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.print_sound
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.print_skip
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.inventory
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.chunk_generated_status
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.controllers
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.gui_type
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.render_mode
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.riding.acceleration
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.riding.direction
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.direction
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.alert_type
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.wire_type
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.circuit_connector_id
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.rail_direction
--- @diagnostic disable-next-line: duplicate-doc-alias
--- @enum defines.rail_connection_direction

---@class uint: integer
---@class double: number
---@class float: number

---@class LocalisedString: string|{[1]: string, [2]: any, [3]: any, [4]: any, [5]: any, [6]: any, [7]: any, [8]: any}

---@class Color table  

---@class CollisionMask: table

---@class SimpleItemStack
---@field name string   
---@field count uint    
---@field health? float 
---@field ammo? uint    
---@field durability? double 

---@class ChartTagSpec
---@field position MapPosition
---@field text string
---@field icon? SignalID[] 
---@field last_user string 
---@field surface LuaSurface 
---@field color? Color 
---@field tag_id? uint 

---@class ScriptArea
---@field area BoundingBox
---@field name string
---@field surface LuaSurface
---@field id uint
---@field color? Color
---@field players? uint[]  
---@field tags? table<string, any>  

---@class SignalID
---@field type string   
---@field name string  

---@class MapPosition
---@field x number
---@field y number

---@class BoundingBox
---@field left_top MapPosition
---@field right_bottom MapPosition

---@class ChunkPosition
---@field x int
---@field y int

---@class Vector
---@field x number
---@field y number



-- Factorio 2.0.47 runtime classes and type aliases (auto-generated, do not edit manually)
---@class LuaAccumulator
---@class LuaAchievementPrototype
---@class LuaAISettings
---@class LuaAmmoCategoryPrototype
---@class LuaArithmeticCombinatorControlBehavior
---@class LuaAutoplaceControlPrototype
---@class LuaBeacon
---@class LuaBeltImmunityEquipment
---@class LuaBinaryCombinatorControlBehavior
---@class LuaBurner
---@class LuaBurnerPrototype
---@class LuaCamera
---@class LuaCharacter
---@class LuaChunkIterator

---@class LuaCircuitNetwork
---@field entity LuaEntity                
---@field circuit_connector_id defines.circuit_connector_id 
---@field network_id uint                
---@field signals table<SignalID, {signal: SignalID, count: int}>? 
---@field wires table<defines.wire_type, LuaCircuitNetwork> 
---@field valid boolean                  
---@field get_signal fun(self: LuaCircuitNetwork, signal: SignalID): int
---@field get_circuit_network fun(self: LuaCircuitNetwork, wire: defines.wire_type): LuaCircuitNetwork?

---@class LuaCliff
---@class LuaCliffPrototype
---@class LuaCommandProcessor
---@class LuaCombinatorControlBehavior
---@class LuaConstantCombinatorControlBehavior
---@class LuaContainer
---@class LuaContainerControlBehavior
---@class LuaControl
---@class LuaControlBehavior
---@class LuaCorpse

---@class LuaCustomChartTag
---@field icon SignalID
---@field last_user? LuaPlayer|nil
---@field position MapPosition
---@field text string
---@field tag_number string
---@field force LuaForce
---@field surface LuaSurface
---@field valid boolean
---@field destroy fun()

---@class LuaCustomInputPrototype
---@class LuaCustomTable
---@class LuaDeciderCombinatorControlBehavior
---@class LuaDecorative
---@class LuaDecorativePrototype
---@class LuaElectricEnergyInterface
---@class LuaElectricPole
---@class LuaElectricPolePrototype

---@class LuaEntity
---@field name string
---@field type string
---@field valid boolean
---@field force LuaForce
---@field surface LuaSurface
---@field position MapPosition
---@field bounding_box BoundingBox
---@field selection_box BoundingBox
---@field unit_number? uint
---@field direction? defines.direction
---@field health? float
---@field ghost_name? string
---@field ghost_type? string
---@field ghost_localised_name? LocalisedString
---@field ghost_localised_description? LocalisedString
---@field mining_progress? double
---@field crafting_progress? double
---@field crafting_recipe? LuaRecipe
---@field items_to_place_this? SimpleItemStack[]
---@field prototype LuaEntityPrototype
---@field vehicle? LuaEntity
---@field driver? LuaEntity|LuaPlayer
---@field passenger? LuaEntity|LuaPlayer
---@field energy? double
---@field temperature? double
---@field fluidbox? LuaFluidBox
---@field logistic_network? LuaLogisticNetwork
---@field logistic_cell? LuaLogisticCell
---@field circuit_connected_entities? table
---@field circuit_connection_definitions? table
---@field circuit_networks? table
---@field control_behavior? LuaControlBehavior
---@field get_inventory fun(self: LuaEntity, inventory: defines.inventory): LuaInventory
---@field insert fun(self: LuaEntity, item: SimpleItemStack): uint
---@field remove_item fun(self: LuaEntity, item: SimpleItemStack): uint
---@field destroy fun(self: LuaEntity)
---@field teleport fun(self: LuaEntity, position: MapPosition, surface?: LuaSurface, raise_teleported?: boolean): boolean
---@field can_insert fun(self: LuaEntity, item: SimpleItemStack): boolean
---@field to_table fun(self: LuaEntity): table
---@field get_fuel_inventory fun(self: LuaEntity): LuaInventory
---@field get_burnt_result_inventory fun(self: LuaEntity): LuaInventory
---@field get_module_inventory fun(self: LuaEntity): LuaInventory
---@field get_output_inventory fun(self: LuaEntity): LuaInventory
---@field get_fluid_inventory fun(self: LuaEntity): LuaInventory
---@field get_rocket_inventory fun(self: LuaEntity): LuaInventory
---@field get_storage_inventory fun(self: LuaEntity): LuaInventory
---@field get_filter_slot fun(self: LuaEntity, index: uint): SimpleItemStack
---@field set_filter_slot fun(self: LuaEntity, index: uint, filter: SimpleItemStack)
---@field get_request_slot fun(self: LuaEntity, index: uint): SimpleItemStack
---@field set_request_slot fun(self: LuaEntity, index: uint, request: SimpleItemStack)
---@field clear_request_slot fun(self: LuaEntity, index: uint)
---@field get_signal fun(self: LuaEntity, signal: SignalID): int
---@field get_merged_signal fun(self: LuaEntity, signal: SignalID): int
---@field get_circuit_network fun(self: LuaEntity, wire: defines.wire_type, circuit_connector?: defines.circuit_connector_id): LuaCircuitNetwork
---@field connect_neighbour fun(self: LuaEntity, target: LuaEntity|table): boolean
---@field disconnect_neighbour fun(self: LuaEntity, target?: LuaEntity|table): boolean
---@field is_connected_to fun(self: LuaEntity, target: LuaEntity): boolean
---@field get_circuit_networks fun(self: LuaEntity): table
-- (Add more fields and methods as needed from the API)

---@class LuaEntityPrototype
---@class LuaEntityPrototypeFlags
---@class LuaEquipment
---@class LuaEquipmentCategoryPrototype
---@class LuaEquipmentGrid
---@class LuaEquipmentGridPrototype
---@class LuaEquipmentPrototype
---@class LuaExplosion
---@class LuaFire
---@class LuaFluidBox
---@class LuaFluidBoxPrototype
---@class LuaFluidEnergySourcePrototype
---@class LuaFluidPrototype
---@class LuaFlowStatistics
---@class LuaFurnace
---@class LuaGameScript
---@class LuaGenericOnOffControlBehavior

---@class LuaGui
---Factorio player GUI root object. Provides access to the player's GUI roots and methods to manipulate GUI elements.
---@field screen LuaGuiElement   # The root element for screen GUIs (modals, dialogs, etc.)
---@field left LuaGuiElement     # The root element for the left side of the screen
---@field center LuaGuiElement   # The root element for the center of the screen
---@field top LuaGuiElement      # The root element for the top of the screen
---@field mod LuaGuiElement      # The root element for mod GUIs (Factorio 2.0+)
---@field relative LuaGuiElement # The root element for relative GUIs (Factorio 2.0+)
---@field valid boolean          # Whether this LuaGui is valid
---@field get_children fun(self: LuaGui): LuaGuiElement[] # Returns all root GUI elements
---@field is_valid fun(self: LuaGui): boolean            # Returns whether the LuaGui is valid
---@field clear fun(self: LuaGui)                        # Destroys all GUI elements created by mods
---@field get_element fun(self: LuaGui, name: string): LuaGuiElement? # Gets a GUI element by name
---@field add fun(self: LuaGui, spec: table): LuaGuiElement           # Adds a new GUI element to a root
---@field remove fun(self: LuaGui, element: LuaGuiElement)            # Removes a GUI element
---@field bring_to_front fun(self: LuaGui, element: LuaGuiElement)    # Brings a GUI element to the front
---@field get_mod_settings fun(self: LuaGui): table                   # Gets mod settings for the GUI
---@field get_style fun(self: LuaGui): LuaStyle                      # Gets the style for the GUI
---@field get_or_create_child fun(self: LuaGui, name: string, spec: table): LuaGuiElement # Gets or creates a child element
---@field get_child fun(self: LuaGui, name: string): LuaGuiElement?  # Gets a child element by name
---@field get_location fun(self: LuaGui): MapPosition                # Gets the location of the GUI
---@field set_location fun(self: LuaGui, location: MapPosition)      # Sets the location of the GUI
---@field get_auto_center fun(self: LuaGui): boolean                 # Gets whether the GUI is auto-centered
---@field set_auto_center fun(self: LuaGui, auto_center: boolean)    # Sets whether the GUI is auto-centered

---@class LuaGroup
---@class LuaHeatBufferPrototype
---@class LuaHeatEnergySourcePrototype
---@class LuaInfinityContainer
---@class LuaInfinityPipe
---@class LuaInserter
---@class LuaInserterPrototype
---@class LuaInventory
---@class LuaItemPrototype
---@class LuaItemRequestProxy
---@class LuaItemStack
---@class LuaItemWithInventory
---@class LuaItemWithLabel
---@class LuaItemWithTags
---@class LuaLamp
---@class LuaLampControlBehavior
---@class LuaLandMine

---@class LuaLinkedContainer
---@field valid boolean
---@field force LuaForce
---@field surface LuaSurface
---@field position MapPosition
---@field get_inventory fun(self: LuaLinkedContainer, inventory: defines.inventory): LuaInventory
---@field link_id uint
---@field link_mode string
---@field link_target LuaLinkedContainer?
---@field link_with fun(self: LuaLinkedContainer, target: LuaLinkedContainer)
---@field unlink fun(self: LuaLinkedContainer)

---@class LuaLogisticCell
---@class LuaLogisticContainer
---@class LuaLogisticContainerControlBehavior
---@class LuaLogisticNetwork
---@class LuaLogisticPoint
---@class LuaLuaCommandProcessor
---@class LuaMapSettings
---@class LuaMarket
---@class LuaMiningDrill
---@class LuaModSettingPrototype
---@class LuaModuleCategoryPrototype
---@class LuaNamedNoiseExpression
---@class LuaNoiseLayerPrototype
---@class LuaPermissionGroup
---@class LuaPermissionGroups

---@class PrintSettings table
---@field color? Color
---@field sound? defines.print_sound
---@field skip? defines.print_skip
---@field sound_path? string
---@field volume_modifier? float
---@field game_state? boolean   # Defaults to true

---@class LuaWall
---@class LuaTrain
---@class LuaTrainStop
---@class LuaTrainStopControlBehavior
---@class LuaTransportBelt
---@class LuaTransportLine
---@class LuaTree
---@class LuaTrivialSmokePrototype
---@class LuaTurret
---@class LuaUnit
---@class LuaUnitGroup
---@class LuaUpgradePlanner
---@class LuaVirtualSignalPrototype

---@class LuaPlayer
-- FIELDS
---@field admin boolean
---@field afk_time uint
---@field character? LuaEntity
---@field color Color
---@field connected boolean
---@field controller_type defines.controllers
---@field crafting_queue_size uint
---@field cursor_stack LuaItemStack
---@field display_resolution {width: uint, height: uint}
---@field display_scale double
---@field driving boolean
---@field force LuaForce
---@field index uint
---@field is_shortcut_toggled table<string, boolean>
---@field mod_settings table<string, {value: any}>
---@field name string
---@field online_time uint
---@field opened? LuaEntity|LuaItemStack|LuaEquipment|LuaEquipmentGrid|LuaPlayer|LuaGuiElement|LuaCustomTable|LuaTransportLine|LuaInfinityContainer|LuaInfinityPipe|LuaLinkedContainer|LuaLogisticContainer|LuaLogisticNetwork|LuaProgrammableSpeaker|LuaTrain|LuaTrainStop|LuaUnitGroup|LuaVirtualSignalPrototype|LuaGui|LuaGuiElement|LuaPermissionGroup|LuaPermissionGroups|LuaRoboport|LuaRoboportControlBehavior|LuaSurface|LuaTile|LuaTilePrototype|LuaTrainStopControlBehavior|LuaTransportBelt|LuaTree|LuaTrivialSmokePrototype|LuaTurret|LuaUnit|LuaUnitGroup|LuaUpgradePlanner|LuaVirtualSignalPrototype|LuaWall
---@field opened_gui_type defines.gui_type
---@field permissions LuaPermissionGroup
---@field position MapPosition
---@field print_entity_info boolean
---@field render_mode defines.render_mode
---@field riding_state {acceleration: defines.riding.acceleration, direction: defines.riding.direction}
---@field selected? LuaEntity
---@field spectator boolean
---@field surface LuaSurface
---@field tag string
---@field ticks_to_respawn? uint
---@field vehicle? LuaEntity
---@field valid boolean
---@field gui LuaGui
---@field walking_state {walking: boolean, direction: defines.direction}
---@field opened_self boolean
---@field opened_unit_number? uint
---@field opened_item? LuaItemStack
---@field opened_signal_id? SignalID
---@field opened_signal_index? uint
---@field opened_signal_mode? string
---@field opened_signal_slot_index? uint
---@field opened_signal_slot_count? uint
---@field opened_signal_slot_name? string
---@field opened_signal_slot_value? any
---@field opened_signal_slot_type? string
---@field opened_signal_slot_signal? SignalID
---@field opened_signal_slot_signal_index? uint
---@field opened_signal_slot_signal_count? uint
---@field opened_signal_slot_signal_name? string
---@field opened_signal_slot_signal_value? any
---@field opened_signal_slot_signal_type? string
-- (Many more opened_signal_* fields omitted for brevity; add as needed)
-- METHODS
---@field add_alert fun(self: LuaPlayer, entity: LuaEntity, alert_type: defines.alert_type, icon?: SignalID, message?: LocalisedString)
---@field add_custom_alert fun(self: LuaPlayer, entity: LuaEntity, icon: SignalID, message: LocalisedString, show_on_map: boolean)
---@field add_item fun(self: LuaPlayer, item: {name: string, count: uint}): uint
---@field begin_crafting fun(self: LuaPlayer, params: {count: uint, recipe: string|LuaRecipe, silent?: boolean}): uint
---@field cancel_crafting fun(self: LuaPlayer, index: uint): boolean
---@field can_insert fun(self: LuaPlayer, item: {name: string, count: uint}): boolean
---@field clear_cursor fun(self: LuaPlayer)
---@field clear_items_inside fun(self: LuaPlayer)
---@field clear_personal_logistics fun(self: LuaPlayer)
---@field clear_personal_trash fun(self: LuaPlayer)
---@field close_map fun(self: LuaPlayer)
---@field connect_to_server fun(self: LuaPlayer, address: string, password?: string)
---@field create_local_flying_text fun(self: LuaPlayer, params: table)
---@field disable_alert fun(self: LuaPlayer, alert_type: defines.alert_type)
---@field enable_alert fun(self: LuaPlayer, alert_type: defines.alert_type)
---@field enable_flashlight fun(self: LuaPlayer)
---@field enable_recipe_notifications fun(self: LuaPlayer)
---@field enable_research_notifications fun(self: LuaPlayer)
---@field enable_tutorial fun(self: LuaPlayer, tutorial: string)
---@field find_entity_ghost fun(self: LuaPlayer, position: MapPosition): LuaEntity?
---@field find_non_colliding_position fun(self: LuaPlayer, name: string, center: MapPosition, radius: double, precision: double, force_to_tile_center?: boolean): MapPosition?
---@field get_active_quick_bar fun(self: LuaPlayer): LuaInventory
---@field get_associated_character fun(self: LuaPlayer): LuaEntity?
---@field get_blueprint_entities fun(self: LuaPlayer): table?
---@field get_crafting_queue fun(self: LuaPlayer): table
---@field get_crafting_queue_size fun(self: LuaPlayer): uint
---@field get_cursor_stack fun(self: LuaPlayer): LuaItemStack
---@field get_friends fun(self: LuaPlayer): string[]
---@field get_inventory fun(self: LuaPlayer, inventory: defines.inventory): LuaInventory
---@field get_main_inventory fun(self: LuaPlayer): LuaInventory
---@field get_quick_bar fun(self: LuaPlayer): LuaInventory
---@field get_vehicle fun(self: LuaPlayer): LuaEntity?
---@field insert fun(self: LuaPlayer, item: {name: string, count: uint}): uint
---@field is_cursor_empty fun(self: LuaPlayer): boolean
---@field is_shortcut_toggled fun(self: LuaPlayer, prototype_name: string): boolean
---@field open_map fun(self: LuaPlayer, position: MapPosition, zoom?: double)
---@field play_sound fun(self: LuaPlayer, params: table)
---@field print fun(self: LuaPlayer, message: string|LocalisedString|table, print_settings?: PrintSettings)
---@field promote fun(self: LuaPlayer)
---@field remove_alert fun(self: LuaPlayer, entity: LuaEntity, alert_type: defines.alert_type)
---@field remove_item fun(self: LuaPlayer, item: {name: string, count: uint}): uint
---@field remove_shortcut fun(self: LuaPlayer, prototype_name: string)
---@field request_translation fun(self: LuaPlayer, localised_string: LocalisedString)
---@field set_controller fun(self: LuaPlayer, type: defines.controllers, character?: LuaEntity)
---@field set_shortcut_toggled fun(self: LuaPlayer, prototype_name: string, toggled: boolean)
---@field teleport fun(self: LuaPlayer, position: MapPosition, surface?: LuaSurface, raise_teleported?: boolean): boolean
---@field unlock_achievement fun(self: LuaPlayer, name: string)
---@field update_selected_entity fun(self: LuaPlayer)
-- (Add more methods as needed from the API)

---@class LuaPowerSwitch
---@class LuaPowerSwitchControlBehavior
---@class LuaProgrammableSpeaker
---@class LuaProgrammableSpeakerControlBehavior
---@class LuaProjectile
---@class LuaPump
---@class LuaPumpPrototype
---@class LuaRailChainSignal
---@class LuaRailPath
---@class LuaRailSegment
---@class LuaRailSignal
---@class LuaRailSignalControlBehavior
---@class LuaRailSignalPrototype

---@class LuaRecipe
---@field name string
---@field localised_name LocalisedString
---@field localised_description LocalisedString
---@field category string
---@field enabled boolean
---@field hidden boolean
---@field energy double
---@field ingredients SimpleItemStack[]
---@field products SimpleItemStack[]
---@field requester_paste_multiplier uint
---@field emissions_multiplier double
---@field allow_decomposition boolean
---@field allow_as_intermediate boolean
---@field allow_intermediates boolean
---@field main_product? string
---@field order string
---@field group LuaGroup
---@field subgroup LuaGroup
---@field valid boolean
---@field prototype LuaRecipePrototype

---@class LuaRecipePrototype
---@field name string
---@field localised_name LocalisedString
---@field localised_description LocalisedString
---@field category string
---@field enabled boolean
---@field hidden boolean
---@field energy double
---@field ingredients SimpleItemStack[]
---@field products SimpleItemStack[]
---@field emissions_multiplier double
---@field allow_decomposition boolean
---@field allow_as_intermediate boolean
---@field allow_intermediates boolean
---@field main_product? string
---@field order string
---@field group LuaGroup
---@field subgroup LuaGroup
---@field valid boolean

---@class LuaRoboport
---@class LuaRoboportControlBehavior
---@class LuaRocketSilo
---@class LuaRocketSiloControlBehavior
---@class LuaRollingStock
---@class LuaSelectionTool
---@class LuaSmoke
---@class LuaSolarPanel
---@class LuaSpeechBubble
---@class LuaSpiderLeg
---@class LuaSpiderVehicle
---@class LuaSpritePrototype
---@class LuaStackFilterInserter
---@class LuaStatistic
---@class LuaStorageTank
---@class LuaStorageTankControlBehavior
---@class LuaStyle

---@class LuaSurface
---@field name string
---@field index uint
---@field peaceful_mode boolean
---@field valid boolean
---@field map_gen_settings table
---@field freeze_daytime boolean
---@field darkness float
---@field always_day boolean
---@field wind_orientation_change float
---@field wind_speed float
---@field daytime float
---@field brightness_visual_weights table
---@field pollution_visual_weights table
---@field show_clouds boolean
---@field generate_with_lab_tiles boolean
---@field print fun(self: LuaSurface, message: string)
---@field create_entity fun(self: LuaSurface, spec: table): LuaEntity
---@field find_entities fun(self: LuaSurface, area?: BoundingBox): LuaEntity[]
---@field find_entity fun(self: LuaSurface, name: string, position: MapPosition): LuaEntity?
---@field get_tile fun(x: number, y: number): LuaTile
---@field set_tiles fun(self: LuaSurface, tiles: table)
---@field request_to_generate_chunks fun(self: LuaSurface, position: MapPosition, radius: uint)
---@field get_random_chunk_position fun(self: LuaSurface): ChunkPosition
---@field get_starting_area_radius fun(self: LuaSurface): double
---@field get_closest fun(self: LuaSurface, position: MapPosition, entities: LuaEntity[]): LuaEntity?
---@field can_place_entity fun(self: LuaSurface, name: string, position: MapPosition, spec: table): boolean
---@field count_entities_filtered fun(self: LuaSurface, spec: table): uint
---@field find_entities_filtered fun(self: LuaSurface, spec: table): LuaEntity[]
---@field find_non_colliding_position fun(self: LuaSurface, name: string, center: MapPosition, radius: double, precision: double, force_to_tile_center?: boolean): MapPosition?
---@field find_non_colliding_position_in_box fun(self: LuaSurface, name: string, search_space: BoundingBox, precision: double, force_to_tile_center?: boolean): MapPosition?
---@field get_chunks fun(self: LuaSurface): table
---@field get_pollution fun(self: LuaSurface, position: MapPosition): double
---@field spill_item_stack fun(self: LuaSurface, position: MapPosition, item_stack: LuaItemStack, enable_looted?: boolean, force?: LuaForce, allow_belts?: boolean): uint
---@field create_decoratives fun(self: LuaSurface, decoratives: table)
---@field create_trivial_smoke fun(self: LuaSurface, smoke_name: string, position: MapPosition)
---@field create_particle fun(self: LuaSurface, particle_name: string, position: MapPosition, movement: Vector, height: double, vertical_speed: double, frame_speed: double)
---@field create_unit_group fun(self: LuaSurface, position: MapPosition, force: LuaForce): LuaUnitGroup
---@field create_entity fun(self: LuaSurface, spec: table): LuaEntity
---@field create_force fun(self: LuaSurface, name: string): LuaForce
---@field destroy_decoratives fun(self: LuaSurface, area: BoundingBox, name?: string, limit?: uint)
---@field destroy_entity fun(self: LuaSurface, entity: LuaEntity)
---@field destroy_force fun(self: LuaSurface, force: LuaForce)
---@field find_tiles_filtered fun(self: LuaSurface, spec: table): LuaTile[]
---@field get_script_area fun(self: LuaSurface, area_id: uint): ScriptArea
---@field get_script_position fun(self: LuaSurface, position_id: uint): MapPosition
---@field get_script_areas fun(self: LuaSurface, tag?: string): ScriptArea[]
---@field get_script_positions fun(self: LuaSurface, tag?: string): MapPosition[]
---@field set_chunk_generated_status fun(self: LuaSurface, position: ChunkPosition, status: defines.chunk_generated_status)
---@field get_chunk_generated_status fun(self: LuaSurface, position: ChunkPosition): defines.chunk_generated_status
---@field get_hidden_tile fun(self: LuaSurface, position: MapPosition): string
---@field set_hidden_tile fun(self: LuaSurface, position: MapPosition, tile: string)
---@field get_resource_counts fun(self: LuaSurface): table<string, uint>
---@field get_trains fun(self: LuaSurface, force?: LuaForce): LuaTrain[]
---@field get_train_stops fun(self: LuaSurface, name?: string, force?: LuaForce): LuaTrainStop[]
---@field get_tile_height fun(self: LuaSurface, position: MapPosition): double
---@field get_tile_properties fun(self: LuaSurface, position: MapPosition): table
---@field get_tile_tags fun(self: LuaSurface, position: MapPosition): table
---@field set_tile_tags fun(self: LuaSurface, position: MapPosition, tags: table)
---@field get_total_pollution fun(self: LuaSurface): double
---@field get_wind_orientation fun(self: LuaSurface): float
---@field set_wind_orientation fun(self: LuaSurface, orientation: float)
---@field get_wind_speed fun(self: LuaSurface): float
---@field set_wind_speed fun(self: LuaSurface, speed: float)
---@field is_chunk_charted fun(self: LuaSurface, chunk_position: ChunkPosition, force?: LuaForce): boolean

---@class LuaTechnology
---@class LuaTechnologyPrototype

---@class LuaTile
---@field name string                 
---@field position MapPosition        
---@field valid boolean              
---@field surface LuaSurface         
---@field hidden boolean             
---@field prototype LuaTilePrototype 
---@field has_hidden_tile boolean    
---@field mineable_properties table  
---@field pollution double           
---@field decorative_names string[]  
---@field entities LuaEntity[]       
---@field collides_with fun(self: LuaTile, mask: string): boolean 

---@class LuaTilePrototype
---@field name string
---@field localised_name LocalisedString
---@field type string
---@field valid boolean
---@field collision_mask CollisionMask

---@class LuaForce
---@field name string                                 
---@field index uint                                  
---@field evolution_factor double                     
---@field evolution_factor_by_pollution double        
---@field evolution_factor_by_time double             
---@field evolution_factor_by_killing_spawners double 
---@field manual_mining_speed_modifier double         
---@field manual_crafting_speed_modifier double       
---@field laboratory_speed_modifier double            
---@field stack_inserter_capacity_bonus uint          
---@field character_logistic_slot_count uint          
---@field character_trash_slot_count uint             
---@field ghost_time_to_live uint                     
---@field item_production_statistics LuaFlowStatistics 
---@field kill_count_statistics LuaFlowStatistics     
---@field item_launched_statistics LuaFlowStatistics  
---@field fluid_production_statistics LuaFlowStatistics
---@field technologies table<string, LuaTechnology>   
---@field players LuaPlayer[]                        
---@field friends LuaForce[]                         
---@field enemies LuaForce[]                         
---@field research_enabled boolean                   
---@field current_research? LuaTechnology            
---@field research_progress double                   
---@field research_queue_enabled boolean             
---@field research_queue LuaTechnology[]             
---@field valid boolean                              
---@field connected_players LuaPlayer[]              
---@field add_chart_tag fun(surface: LuaSurface, spec: table): LuaCustomChartTag
---@field is_chunk_charted fun(self: LuaForce, surface: LuaSurface, chunk_position: ChunkPosition): boolean 
---@field chart fun(self: LuaForce, surface: LuaSurface, area: BoundingBox) 
---@field chart_all fun(self: LuaForce, surface: LuaSurface) 
---@field clear_chart fun(self: LuaForce, surface: LuaSurface)
---@field cancel_current_research fun(self: LuaForce) 
---@field reset_technology_effects fun(self: LuaForce)
---@field enable_all_recipes fun(self: LuaForce) 
---@field disable_all_recipes fun(self: LuaForce)
---@field reset_recipes fun(self: LuaForce) 
---@field reset_technologies fun(self: LuaForce)
---@field get_friend fun(self: LuaForce, other: LuaForce): boolean 
---@field set_friend fun(self: LuaForce, other: LuaForce, friend: boolean) 
---@field get_cease_fire fun(self: LuaForce, other: LuaForce): boolean 
---@field set_cease_fire fun(self: LuaForce, other: LuaForce, cease_fire: boolean)
---@field get_spawn_position fun(self: LuaForce, surface: LuaSurface): MapPosition 
---@field set_spawn_position fun(self: LuaForce, position: MapPosition, surface: LuaSurface) 
---@field get_saved_technology_progress fun(self: LuaForce, technology: string): double 
---@field set_saved_technology_progress fun(self: LuaForce, technology: string, progress: double) 
---@field print fun(self: LuaForce, message: LocalisedString) 
---@field find_chart_tags fun(surface: LuaSurface|string|uint, area?: BoundingBox): LuaCustomChartTag[]
---@overload fun(self: LuaForce, surface: LuaSurface|string|uint, area?: BoundingBox): LuaCustomChartTag[]
-- (Add more fields and methods as needed from the API)

---@class LuaGuiElement
---@field name string
---@field type string
---@field parent LuaGuiElement?
---@field children LuaGuiElement[]
---@field style LuaStyle
---@field tags table<string, any>
---@field index uint
---@field valid boolean
---@field visible boolean
---@field enabled boolean
---@field caption LocalisedString
---@field tooltip LocalisedString
---@field style_mods table<string, any>
---@field elem_value any
---@field value any
---@field text string
---@field number number
---@field selected_index uint
---@field selected_tab_index uint
---@field state boolean
---@field items string[]
---@field item string
---@field sprite string
---@field color Color
---@field direction string
---@field drag_target LuaGuiElement?
---@field location MapPosition
---@field auto_center boolean
---@field destroy fun()
---@field clear fun(self: LuaGuiElement)
---@field add fun(self: LuaGuiElement, spec: table): LuaGuiElement
---@field remove fun(self: LuaGuiElement)
---@field bring_to_front fun(self: LuaGuiElement)
---@field get_mod_settings fun(self: LuaGuiElement): table
---@field get_style fun(self: LuaGuiElement): LuaStyle
---@field get_index fun(self: LuaGuiElement): uint
---@field get_parent fun(self: LuaGuiElement): LuaGuiElement?
---@field get_children fun(self: LuaGuiElement): LuaGuiElement[]
---@field get_or_create_child fun(self: LuaGuiElement, name: string, spec: table): LuaGuiElement
---@field get_child fun(self: LuaGuiElement, name: string): LuaGuiElement?
---@field get_caption fun(self: LuaGuiElement): LocalisedString
---@field set_caption fun(self: LuaGuiElement, caption: LocalisedString)
---@field get_tooltip fun(self: LuaGuiElement): LocalisedString
---@field set_tooltip fun(self: LuaGuiElement, tooltip: LocalisedString)
---@field get_style_mods fun(self: LuaGuiElement): table<string, any>
---@field set_style_mods fun(self: LuaGuiElement, mods: table<string, any>)
---@field get_tags fun(self: LuaGuiElement): table<string, any>
---@field set_tags fun(self: LuaGuiElement, tags: table<string, any>)
---@field get_value fun(self: LuaGuiElement): any
---@field set_value fun(self: LuaGuiElement, value: any)
---@field get_text fun(self: LuaGuiElement): string
---@field set_text fun(self: LuaGuiElement, text: string)
---@field get_number fun(self: LuaGuiElement): number
---@field set_number fun(self: LuaGuiElement, number: number)
---@field get_selected_index fun(self: LuaGuiElement): uint
---@field set_selected_index fun(self: LuaGuiElement, index: uint)
---@field get_selected_tab_index fun(self: LuaGuiElement): uint
---@field set_selected_tab_index fun(self: LuaGuiElement, index: uint)
---@field get_state fun(self: LuaGuiElement): boolean
---@field set_state fun(self: LuaGuiElement, state: boolean)
---@field get_items fun(self: LuaGuiElement): string[]
---@field set_items fun(self: LuaGuiElement, items: string[])
---@field get_item fun(self: LuaGuiElement): string
---@field set_item fun(self: LuaGuiElement, item: string)
---@field get_sprite fun(self: LuaGuiElement): string
---@field set_sprite fun(self: LuaGuiElement, sprite: string)
---@field get_color fun(self: LuaGuiElement): Color
---@field set_color fun(self: LuaGuiElement, color: Color)
---@field get_direction fun(self: LuaGuiElement): string
---@field set_direction fun(self: LuaGuiElement, direction: string)
---@field get_drag_target fun(self: LuaGuiElement): LuaGuiElement?
---@field set_drag_target fun(self: LuaGuiElement, target: LuaGuiElement?)
---@field get_location fun(self: LuaGuiElement): MapPosition
---@field set_location fun(self: LuaGuiElement, location: MapPosition)
---@field get_auto_center fun(self: LuaGuiElement): boolean
---@field set_auto_center fun(self: LuaGuiElement, auto_center: boolean)
