local Constants = {
  PREFIX = "tf_",
  settings = {
    DEFAULT_LOG_LEVEL = "production",
    PROFILER_CONTROL_MODE = "off",
    PROFILER_MAX_TICKS = 35 * 60,
    PROFILER_OUTPUT_FILE = "teleport-favorites-profile.txt",
    CHART_TAG_CLICK_RADIUS = 10,
    CHART_TAG_TEXT_MAX_LENGTH = 1024,
    TAG_TEXT_MAX_LENGTH = 256,
    DEFAULT_SNAP_SCALE = 1,
    DEFAULT_MAX_FAVORITE_SLOTS = 10,
    MAX_FAVORITE_SLOTS_SETTING = "max-favorite-slots",
    FAVE_BAR_SLOT_PREFIX = "fave_bar_slot_",
    TELEPORT_HISTORY_LABEL_MAX_DISPLAY = 27,
    DEFAULT_SLOT_LABEL_MODE = "off",
    SLOT_LABEL_MODE_SETTING = "slot-label-mode",
    DEFAULT_HISTORY_UPDATE_INTERVAL = 30,
    MIN_UPDATE_INTERVAL = 5,
    MAX_UPDATE_INTERVAL = 59,
    GPS_PAD_NUMBER = 3,
    BLANK_GPS = "1000000.1000000.1",
    SEQUENTIAL_HISTORY_RESOLUTION = 32,
    FAVORITES_ON = "favorites_on",
    SHOW_TELEPORT_HISTORY = "enable_teleport_history",
    MP_BISECT_MODE_SETTING = "tf-mp-bisect-mode",
    BOUNDING_BOX_TOLERANCE = 4,
  },
}
return Constants
