
# Trivial change to force GitHub Actions workflow re-index (2025-07-24)

name: Release Mod

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.0.15)'
        required: true

jobs:
  build-and-release:
    runs-on: windows-latest
    environment: release-approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if needed)
        run: |
          python -m pip install --upgrade pip

      - name: Copy production files to .dist
        run: python .scripts/copy_for_deploy.py

      - name: Strip comments from Lua files in .dist
        run: python .scripts/strip_comments.py

      - name: Update info.json version in .dist
        run: |
          $infoPath = ".dist/info.json"
          if (Test-Path $infoPath) {
            $json = Get-Content $infoPath -Raw | ConvertFrom-Json
            $json.version = "${{ github.event.inputs.version }}"
            $json | ConvertTo-Json -Depth 32 | Set-Content $infoPath -Encoding UTF8
          } else {
            Write-Error "info.json not found in .dist; build failed to stage required files."
          }

      - name: Validate changelog.txt format in .dist
        run: python .scripts/validate_changelog.py

      - name: Validate thumbnail.png present in .dist
        run: |
          if (!(Test-Path ".dist/thumbnail.png")) {
            Write-Error "thumbnail.png is missing from .dist. Ensure it's added at repo root or graphics/logo_144.png exists for fallback."
          }

      - name: Wrap .dist contents in versioned mod folder
        run: |
          $modFolder = "TeleportFavorites_${{ github.event.inputs.version }}"
          $target = ".dist/$modFolder"
          if (-not (Test-Path $target)) { New-Item -ItemType Directory -Path $target | Out-Null }
          Get-ChildItem ".dist" -Force | Where-Object { $_.Name -ne $modFolder } | ForEach-Object {
            Move-Item -Path $_.FullName -Destination $target
          }

      - name: Zip the .dist directory for release
        run: |
          $modFolder = "TeleportFavorites_${{ github.event.inputs.version }}"
          Compress-Archive -Path ".dist/$modFolder" -DestinationPath "TeleportFavorites_${{ github.event.inputs.version }}.zip" -Force

      - name: List files in .dist
        run: Get-ChildItem .dist -Recurse

      - name: Verify diagnostic annotations preserved (debug)
        run: |
          Write-Host "Checking slot_interaction_handlers.lua first 3 lines:"
          Get-Content .dist\TeleportFavorites_${{ github.event.inputs.version }}\core\control\slot_interaction_handlers.lua | Select-Object -First 3
          Write-Host "Checking settings.lua first 3 lines:"
          Get-Content .dist\TeleportFavorites_${{ github.event.inputs.version }}\core\cache\settings.lua | Select-Object -First 3

      - name: Upload .dist directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TeleportFavorites_${{ github.event.inputs.version }}
          path: .dist
          include-hidden-files: true
          if-no-files-found: error

      - name: Create GitHub Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: TeleportFavorites ${{ github.event.inputs.version }}
          body_path: .dist\TeleportFavorites_${{ github.event.inputs.version }}\changelog.txt
          files: TeleportFavorites_${{ github.event.inputs.version }}.zip

